getter:
  name: "Dummy"
  data_path: "DATA/preprocessed/tennis.csv"
  data_length: 10

sender:
  name: "Dummy"




forecaster:
  name: "ReverseOdd"

picker:
  name: "MostProbableByMatch"

sizer:
  name: "Kelly"

treasurer:
  name: "Dummy"


